version: "2"

run:
  timeout: 5m

formatters:
  enable:
    - gofmt
  exclusions:
    paths:
      - "**_test.go"

linters:
  enable:
    - govet
    - staticcheck
    - ineffassign
    - misspell
    - gocyclo
    - errcheck
    - unused

  settings:
    gocyclo:
      min-complexity: 15
    errcheck:
      exclude-functions:
        - (github.com/tggo/goSentencePiece.Tokenizer).Encode
        - (github.com/tggo/goSentencePiece.Tokenizer).Decode

  exclusions:
    rules:
      - path: "_test\\.go"
        linters:
          - errcheck
          - gocyclo

issues:
  exclude-dirs:
    - proto
