version: "2"

run:
  timeout: 5m

linters:
  enable:
    - gofmt
    - govet
    - staticcheck
    - ineffassign
    - misspell
    - gocyclo
    - errcheck
    - gosimple
    - unused

  settings:
    gocyclo:
      min-complexity: 15

issues:
  exclude-dirs:
    - proto
